### ISSUE TITLE
No proximity routing

### ISSUE THREAD

**Issue by sjoshi10** [octodns/octodns-cloudflare#101]
OctoDNS works well when it comes to creating record but there is no functionality that creates LoadBalancers and node pools. I haven't seen any information in the docs. I was wondering if you guys plan to add this in the future. This is important for because I use proxmity routing in CF.

**Comment by ross** [comment]
Generally octoDNS's focus is on creating a unified set of functionality that is supported across all of it's providers to enable things like [split authority](https://github.blog/2017-04-27-enabling-split-authority-dns-with-octodns). CloudFlare's proximity routing is pretty unique to CF and only has some conceptual overlap with Route53's. I haven't run across any other providers that support it. 

So that's why it isn't already a supported thing, it's just not what octoDNS is/was focused on. That said there are provisions for providers to support one-off functionlity, which results in octoDNS being "only" a DNS config management, which imo it is still is the best option for :grin:

I'm not deeply familiar with CF's proximity routing stuff, but the configuration for it would likely look something likie:

```yaml
foo:
  octodns:
    cloudflare:
      <whatever-goes-here...>
  type: A
  value: ...
```

The above is the way somethig CF specific would be configured. The details of what that would look like and how it would be implemented in the provider would be the hard part of implementing it. PRs are welcome, but outside of contracted development it's probably not something I'm likely to get to in the near future.
