### ISSUE TITLE
Handling of Worker records

### ISSUE THREAD

**Issue by barnumbirr** [octodns/octodns-cloudflare#53]
Hi,

[from reading the Cloudflare documentation on handling DNS records](https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-list-dns-records), I gathered that adding support for Worker records to octodns would not be possible.

My question therefore is: is there a way to manage a zone `example.com` with a Cloudflare proxied record type `Worker` pointing to `worker-example.com` and TTL set to `Auto` without having the octodns delete said `Worker` record at every update? `Worker` records are added automagically by Clouflare Workers "Custom Domain" section and can't even be edited from within the zone view itself.

Thanks in advance.

**Comment by ross** [comment]
Dunno the specifics of those records, but if there's a type or name pattern to them you can potentially use one of the filtering processors to ignore them https://github.com/octodns/octodns/blob/main/octodns/processor/filter.py. Failing that if there's something else to key off of a Cloudflare worker processor may make sense or it may be necessary to put some logic into the provider itself. Without seeing the details of the record data it's hard to say.

**Comment by barnumbirr** [comment]
As the specific record is for a personal project, I don't mind sharing more details of the record data. What information would you specifically need? Would a screenshot of the record details and the corresponding "Custom Domain" section of the worker be enough?

I believe [this documentation describes the API calls executed by the Cloudflare UI to attach a worker to a DNS zone and hostname](https://developers.cloudflare.com/api/operations/worker-domain-attach-to-domain).

**Comment by ross** [comment]
If you're comfortable making minor changes to octodns_cloudflare you should stick 

```python
from pprint import pprint
pprint(records)
```

between these two lines https://github.com/octodns/octodns-cloudflare/blob/8b98b5db67afd12e04926bce7ff2e3104568cb8f/octodns_cloudflare/__init__.py#L453-L454

and then copy and paste in the data for the worker record(s). 

That should provide the details of what's coming back from the DNS API for those records and then we can see if there's anything specific to key off of and otherwise. go from there.

**Comment by barnumbirr** [comment]
I don't mind having to edit `octodns_cloudflare` locally however I'm confused by the instructions. What do you mean by:

> and then copy and paste in the data for the worker record(s).

Would you mind explaining this in more detail?

**Comment by ross** [comment]
If that `pprint` snippet is added and an `octodns-sync` run, presumably one where you're seeing the plan is to delete the worker records, it will dump out all of the record data for the zone. I don't have any Worker records so can't show an example of that, but the block below is a copy-n-paste of one of the records printed when I added the `pprint` and ran `octodns-sync --config-file=config/dev.yaml`.

The hope is that there's something obvious about the records to key off of so that they can be ignored. 

```python
...
 {'comment': None,
  'content': '52.14.23.59',
  'created_on': '2023-08-12T15:50:05.363934Z',
  'id': '72c1751decd543e3e8052098c169b66c',
  'locked': False,
  'meta': {'auto_added': False,
           'managed_by_apps': False,
           'managed_by_argo_tunnel': False,
           'source': 'primary'},
  'modified_on': '2023-08-12T15:50:05.363934Z',
  'name': 'exxampled.com',
  'proxiable': True,
  'proxied': False,
  'tags': [],
  'ttl': 3600,
  'type': 'A',
  'zone_id': 'a3d20bc5d2a176440caa4253d4695104',
  'zone_name': 'exxampled.com'},
...
```

If you're not familar enough with python and where and how to insert the `pprint` lines don't worry about it. I or someone else can poke around in the future and try and figure something out.

**Comment by barnumbirr** [comment]
Got it, apologies for being thick. Here's the requested output specific to the worker record:

```json
 {'comment': None,
  'content': '100::',
  'created_on': '2023-08-29T18:15:56.934319Z',
  'id': '9aad0485a1accecc2fb41d50ba2a3603',
  'locked': False,
  'meta': {'auto_added': False,
           'managed_by_apps': False,
           'managed_by_argo_tunnel': False,
           'origin_worker_id': 'fdc30fbfb57c836f22721ff0906015487743cd30',
           'source': 'primary'},
  'modified_on': '2023-08-29T18:15:56.934319Z',
  'name': '0xff.tf',
  'proxiable': True,
  'proxied': True,
  'tags': [],
  'ttl': 1,
  'type': 'AAAA',
  'zone_id': '610691feda2ba25826a172d617d89380',
  'zone_name': '0xff.tf'}]
```

**Comment by ross** [comment]
So this bit can definitely be used to put some special logic into the `CloudflareProvider` to ignore these records.

```python
           'origin_worker_id': 'fdc30fbfb57c836f22721ff0906015487743cd30',
```

I don't see anything there which would allow a processor to easily ignore them automatically. Best bet is probably to add placeholders for them to your config, but flag them as ignored:

```yaml
'':
  - octodns:
        ignored: true
    type: AAAA
    # this won't be used, you can put anything you want
    value: dead::42
```

Will leave this open to track the need to find a build-in way to handle this case.

**Comment by barnumbirr** [comment]
Works a treat, thank you. Even if this isn't handled by `CloudflareProvider ` in the future, at least now my worker doesn't get disabled by each octodns run.
